# Generated by Django 2.0.1 on 2018-02-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180212_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_range',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Max amount'),
        ),
        migrations.AddField(
            model_name='category',
            name='min_range',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Min amount'),
        ),
    ]
