# Generated by Django 2.0.1 on 2018-03-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180303_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='consolation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Consolation '),
        ),
        migrations.AddField(
            model_name='category',
            name='seller',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Seller Share'),
        ),
        migrations.AddField(
            model_name='category',
            name='sponser',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sponser Share'),
        ),
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Co-operation Amount'),
        ),
        migrations.AlterField(
            model_name='category',
            name='max_range',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Max Gift Amount'),
        ),
        migrations.AlterField(
            model_name='category',
            name='min_range',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Min Gift Amount'),
        ),
    ]
