# Generated by Django 2.0.1 on 2018-03-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180308_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='00000000', max_length=8, verbose_name='Product Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('LP', 'LAPTOP'), ('MB', 'MOBILE'), ('TV', 'LED TV'), ('FR', 'FRIDGE'), ('WM', 'WASHING MACHINE'), ('WP', 'WATER PURIFIER'), ('KU', 'KITCHEN UTENSIL')], default='MB', max_length=2),
        ),
    ]
