# Generated by Django 2.0.1 on 2018-01-21 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('product', models.CharField(max_length=12)),
                ('sponser', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now=True)),
                ('key_1', models.CharField(max_length=10)),
                ('key_2', models.CharField(max_length=10)),
                ('key_3', models.CharField(max_length=10)),
                ('key_4', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MISS', 'Miss.'), ('SMT', 'Smt.'), ('MS', 'M/S')], default='MR', max_length=4)),
                ('mobile', models.CharField(max_length=13)),
                ('adhaar', models.CharField(blank=True, max_length=12)),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_account', models.CharField(max_length=20)),
                ('bank_ifsc', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100, verbose_name='Nearest Service Center')),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=6)),
                ('image', models.ImageField(default='user/none/no_img.png', upload_to='user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
