# Generated by Django 2.0.1 on 2018-01-23 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20180121_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='key_1',
        ),
        migrations.RemoveField(
            model_name='member',
            name='key_2',
        ),
        migrations.RemoveField(
            model_name='member',
            name='key_3',
        ),
        migrations.RemoveField(
            model_name='member',
            name='key_4',
        ),
        migrations.AddField(
            model_name='member',
            name='first_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='prize_win',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='second_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='key_first',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, related_name='member_key_first', to='member.Token'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='key_four',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, related_name='member_key_four', to='member.Token'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='key_three',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, related_name='member_key_third', to='member.Token'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='key_two',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, related_name='member_key_second', to='member.Token'),
            preserve_default=False,
        ),
    ]
