# Generated by Django 2.0.1 on 2018-01-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20180123_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='key_first',
        ),
        migrations.RemoveField(
            model_name='member',
            name='key_four',
        ),
        migrations.RemoveField(
            model_name='member',
            name='key_three',
        ),
        migrations.RemoveField(
            model_name='member',
            name='key_two',
        ),
        migrations.RemoveField(
            model_name='token',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='token',
            name='pin',
        ),
        migrations.AddField(
            model_name='member',
            name='key_1',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='member',
            name='key_2',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='member',
            name='key_3',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='member',
            name='key_4',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_level',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='prize_win',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='second_level',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
